# Docker Compose file for Vapor
#
x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
 app:
    image: kicsipixel/gyms_in_cloud:latest
    environment:
      <<: *shared_environment
    env_file:
      - .env.production
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--hostname", "0.0.0.0", "--port", "8080"]
 migrate:
    image: kicsipixel/gyms_in_cloud:latest
    environment:
      <<: *shared_environment
    env_file:
      - .env.production
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
 revert:
    image: kicsipixel/gyms_in_cloud:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    env_file:
      - .env.production
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
 pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env.production
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
   pgadmin-data:
